### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by elzinko** [dawstudiocenter/AbletonLiveMidiRemoteScripts#4]
Hi!

Is there an already existing documentation for those scripts ? Otherwise I will try to write one.

I think I manage to make nearly all the feature works but It remains a mystery for me : one day I manage to make the clip launch buttons (from 32 to 39) have a momentary function using the left shit button, so that they did not triggered the clips, but they triggered only the CC (32 to 39) which was a big improvement for my use... 

Is this functionality already available and how to make it work cause I never managed to make it work again...

**Comment by ValKon112** [comment]
Hello Elzinko!
If I understand your question correctly, then: in order to avoid launching clips when using the CC32-CC39 buttons for other needs, it is enough to change the value 32 to 0 in line 16 of the Consts.py file.
