### ISSUE TITLE
stopped working with 10.1.x

### ISSUE THREAD

**Issue by decoderrrr** [dawstudiocenter/AbletonLiveMidiRemoteScripts#5]
The Control Surfaces doesn't show up in Live 10.1.x preferences dropdown anymore.

**Comment by yevt** [comment]
@dawstudiocenter  Please, could you fix it? This script, for sure, is the best one for Sl MK2. I miss it. We miss it :)

**Comment by dawstudiocenter** [comment]
it still works for me at least up to 10.1.13.

**Comment by trex20xx** [comment]
> it still works for me at least up to 10.1.13.

Hi, also for me it works, however would you please update it to work for ableton 11? no need to change anything just to make it work. Great job btw.
