### ISSUE TITLE
Not working in Ableton 11.x.x

### ISSUE THREAD

**Issue by trex20xx** [dawstudiocenter/AbletonLiveMidiRemoteScripts#6]
Hello,

Would you be willing to update the script to make it work with Ableton 11.x.x?
As for now it works with all 10.x.x versions. 
Thank you. Great work btw !

**Comment by dawstudiocenter** [comment]
The SL Ultimate Control and SL Ultimate Extra device are now fully compliant with python 3.x and Ableton Live 11. Enjoy !

**Comment by trex20xx** [comment]
Thank you so much, and much appreciated for the hard work. If i may, would there be any chance for a more in depth tutorial? I think we're missing a bit here.

Other than that...great work!

**Comment by justdatruth** [comment]
Another grateful user here, just wanted to say thank you for your efforts in getting this script working with Live 11. Its very much appreciated
